### ISSUE TITLE
Allow threshold on objective to update surrogate function

### ISSUE THREAD

**Issue by Engineero** [fmfn/BayesianOptimization#102]
It may be nice to allow a threshold on the value of the objective function, results under which are not included in updating the surrogate objective function (basically skip the update step and move on to the next sample).

My motivation is a noisy objective function: hyperparameter optimization for a machine learning problem wherein the training process occasionally fails to converge due to bad initialization. This results in an objective function evaluation that is a major outlier, and would likely be much more reasonable with the exact same hyperparameters and a different initialization. In cases where this sort of thing is known to occur, it might be nice to provide a minimum value of the objective function, under which an iteration is just discarded rather than updating your surrogate.

**Comment by fmfn** [comment]
I think this issue is better handled by the user and shouldn't be a feature of this package. Since you know what kinds of pitfalls your optimization problem may have you can add that logic to the function you are optimizing. So, instead of returning the raw value of your loss, you could check and/or cap it first.
