### ISSUE TITLE
How is optimizer.suggest randomized?

### ISSUE THREAD

**Issue by nikhilwbhatia** [fmfn/BayesianOptimization#139]
1. I noticed that one can call optimizer.suggest multiple times without calling the black box function or registering any results with the optimizer and still receive different suggested points. Can you help me understand why all the suggested points are different if the acquisition function isn't changing in between the calls?

2. Given this, in a single suggest/eval/register loop could I realistically call optimizer.suggest x number of times (receiving x different points), run the black_box function on these points in parallel, and then register these x output values with their corresponding inputs (in that specific order). If this works, is there an easy explanation as how this differs statistically from only suggesting/eval one input at a time? 

Thank you!

**Comment by fmfn** [comment]
1. The `suggest` method will return random points within the boundaries specified if no observations have been registered yet. If, however, observations have been registered, then `suggest` should behave deterministically. There's one caveat though, since the suggestion is based on the optimization of the acquisition function, if it is a hard function to optimize it is possible that you will see different suggestions as a result of the proxy optimization getting stuck in local maxima of the acquisition function.
2. The answer is no. Pathological behaviour aside, multiple calls to the `suggest` method will return the same point until a new observation is registered.
