### ISSUE TITLE
Non-python black box function

### ISSUE THREAD

**Issue by mikecmpbll** [fmfn/BayesianOptimization#142]
Is there a way of using this library without an integrated black box function? Some other libraries provide a way to input f(x) for each interation and get the recommended x for the next run out? 

This is useful for integrating into non-python problems and real world problems.

**Comment by fmfn** [comment]
You're definitely free to optimize non-python (or even non-digital) functions. As long as you can report back what the return value for a given parameter combination was you should be ok.

Now, in order to see this in action I suggest you take a look at:
1. First session of the [advanced tour](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb)
2. The following (now closed) [issue](https://github.com/fmfn/BayesianOptimization/issues/138)
3. This package working [asynchronously](https://github.com/fmfn/BayesianOptimization/blob/master/examples/async_optimization.py).

In the advanced tour you will be exposed to the Suggest-Evaluate-Register Paradigm, which gives you all the flexibility you need to use non-python functions. In the issue discussion I give an example (that doesn't actually work, but paints a clear picture) of how you can decouple getting suggestions, evaluating results and registering observations. Finally, in the async example, you can actually see it all working.
