### ISSUE TITLE
Question on generating multiple unique suggestions

### ISSUE THREAD

**Issue by dstauffer11m** [fmfn/BayesianOptimization#152]
I'm using the suggest-evaluate-register paradigm, performing my function evaluations separately in parallel. Once we've moved past the initial random search stage and registered the first round of points, the suggest function now always returns the value suggested by utils.acq_max. However, I want to generate N different suggestions to evaluate at once since my function is expensive but parallelizable. Is there a suggested way to generate these suggestions? 

My initial idea is to get a suggestion, register it as, say, the average value of the previous round, get another suggestion, etc.. repeat N times. This seems like it would space out suggestions reasonably well. Then actually evaluate these in parallel and register them with their real values. This would require changing the code a bit to allow overwriting already-registered values. Would this cause deeper issues with the modeled GP distributions?

**Comment by fmfn** [comment]
Checkout the discussing in this (now closed) [issue](https://github.com/fmfn/BayesianOptimization/issues/138), I believe it will make it a bit more clear. The gist is: register right before asking for a suggestion. So, if you have concurrent (not just parallel) workers, just make sure that each, on their on, register their last result before asking for a new probe point.

Also this [script](https://github.com/fmfn/BayesianOptimization/blob/master/examples/async_optimization.py) is a fully working example of using this library in a distributed fashion, take a look at it and see if it helps.

**Comment by dstauffer11m** [comment]
Yes, I read through the async example and I understand the algorithm is deterministic so what I'm asking doesn't make 100% sense. If I understand correctly, the async example and your example on #138 are just doing separate runs of the algorithm concurrently? That may be wrong. But if so, it's not really what I want to do.

Were I to just register with a placeholder value and later register with the real value, would that cause any issues that you know of?

**Comment by fmfn** [comment]
> If I understand correctly, the async example and your example on #138 are just doing separate runs of the algorithm concurrently?

No, that would defeat the purpose. In both cases they are sharing the same underlying BayesianOptimization instance, but evaluating the function concurrently.

There is no registering placeholders, or registering approximate points (as you mentioned before) since this would be incompatible / mess up with the gaussian process powering the method.

As you said, the algorithm is deterministic, so the only way of getting a different suggestion (after an observation was made) is to register a new observation. So, to reiterate, the gist of the idea is you evaluate your function however you like, in parallel, concurrently, offline, in java, doesn't matter, provided that, once you're done evaluating your function you register the new observation and ask for a suggestion immediately after.

Machines A and B receive some random suggestions and start evaluating the function, both share the same instance of BayesianOptimization as their oracle. Machine B finishes first, registers the observation and gets a new suggestion. Now the optimizer knows of one observation. Machine A finishes it's first run, reports back the result and asks for a new suggestion. This suggestion will be different than what B got since the optimizer has been exposed to two observations now. This keeps going, every time a machine finishes evaluating the function it will report the result and ask for a suggestion, making sure it always get a new suggestion.

Does it make sense?

**Comment by dstauffer11m** [comment]
Yes that makes sense, it just isn't compatible with my function evaluation setup. I can run the expensive function in parallel but I have to submit all N suggestions at once and get all the responses at once as well. 

Would you mind explaining a bit more how registering placeholders would mess up the underlying GP? I could just store all points ever evaluated and rebuild the GP every round so my placeholder values aren't ever in the actual model, I suppose.

**Comment by fmfn** [comment]
> I can run the expensive function in parallel but I have to submit all N suggestions at once and get all the responses at once as well.

That's ok. When all function evaluations are done you send them to the same BO instance. At this point, register one at a time, asking for a suggestion immediately after, and storing them in order. Send all the suggestions back to the function evaluators.

With the exception of the very first round, when random suggestions are used, all the subsequent rounds will involve the evaluation of the function completing, an observation being registered, and a new suggestion being generated. It doesn't matter how many function are being evaluated, in parallel or not, or whatever.

> Would you mind explaining a bit more how registering placeholders would mess up the underlying GP?

You register observations, I don't even know what a placeholders observation means.

**Comment by dstauffer11m** [comment]
Ah, I understand now. That fixes all my issues. Thank you!

As for placeholders, I just meant I'd register a "roughly average" value for each suggestion and later register the real value when I had it. Maybe I'll try that and compare but your above ordering of steps makes more sense.
