### ISSUE TITLE
How to input complicated constraints in Bayesian Optimization that is not just lower and upper bound using Python?

### ISSUE THREAD

**Issue by RuoyunChen** [fmfn/BayesianOptimization#189]
Hi, I'm wondering is the package only capable of dealing with the simple lower and upper bound constraint? What if I have more complicated constraint (it is to do with calling another self-defined function), how do I input constraints like that?
Thanks!

**Comment by ben-arnao** [comment]
Would anyone be interested if we tried to add additional sampling distributions other than a uniform?

**Comment by julian-belina** [comment]
It would be really great if self defined functions could be applied as constraints. I have been doing some reserach on Bayesian optimization packages but non of the packages that are still maintained offers such functionality. 
Only spearmint(https://github.com/HIPS/Spearmint) is able to do so but still utlizes python 2.7 and can only be called via command line input.
Gpoptflow(https://gpflowopt.readthedocs.io/en/latest/notebooks/constrained_bo.html) implemented equality constraints but no inequality constraints. Also it dosent seem that there is any current development on the repository either.

**Comment by sgbaird** [comment]
@julian-belina [Ax](https://ax.dev/docs/bayesopt.html) (unaffiliated) supports a variety of constraints out of the box. [BoTorch](https://botorch.org/) (backbone of Ax, I'm also unaffiliated) supports equality, inequality, and nonlinear constraints (the last one has the caveat of requiring gradients, which can get tricky). Ax is [on its way](https://github.com/facebook/Ax/issues/769) to getting the plumbing in order to support nonlinear constraints soon (again, you have to supply gradients).

**Comment by sgbaird** [comment]
Differentiable, nonlinear inequality constraints are now supported in Ax, though it can take some care to get these implemented since it requires applying some BoTorch transforms manually. See https://github.com/facebook/Ax/issues/769
