### ISSUE TITLE
BayesianOptimization maximize method number of actual iterations doesn't match the argument n_iter

### ISSUE THREAD

**Issue by R-Araripe** [fmfn/BayesianOptimization#197]
I am trying to use the BayesianOptimization class as  in the example provided in this repo "sklearn_example.py"

```
optimizer = BayesianOptimization(f=rfc_crossval, pbounds=pbounds, verbose=2)
optimizer.maximize(n_iter=10)
```

The problem is no matter the value I give to n_iter, the number of iterations it actually does (I can observed it in the table printed  because verbose=2) never matches. if I put  `n_iter=10`, it does 15 iterations; if I put `n_iter=3`; it does 8. if I put `n_iter=15`, it does 20. It seems that there is a pattern of always doing 5 iterations more than specified..

Is  that the expected behavior?

Cheers!

**Comment by raff7** [comment]
I believe that it has to do with the fact that you call maximize without specifying 'init_points'. if you don't specify it its default value is 5. this means that it will do 5 trials with randomly selected points, followed by 10 iterations of the actual bayesian optimization algorithm.
It is indeed an expected behaviour

**Comment by R-Araripe** [comment]
Yes, that's it. Thank you!
