### ISSUE TITLE
Couple questions about the correct use of the library.

### ISSUE THREAD

**Issue by ar-valdez** [fmfn/BayesianOptimization#207]
I have gone through the next demo tutorial explanation...

> https://github.com/fmfn/BayesianOptimization/blob/master/examples/exploitation_vs_exploration.ipynb

And as many of us tried to adapted to our personal needs. Yet not successfully, hope to hear advises. Lets start with some definitions.

My model corresponds to a exponential decrease function,
`def model(c,I,t):`
       ` return I*np.exp(-c*t)`
I want to fit/adjust a GP regressor to the next target function:
`def my_target(t):
    return model(0.2,5,t)`

The ranges of variations of the parameters are given in the next dictionary:
`pbounds = {'c': (0, 0.4), 'I': (8, 10), 't':(0,10)}`

Here comes the first TRUE question `bo = BayesianOptimization(model,pbounds,verbose=2,random_state=1)` How does `bo` received information to fit to `target`???

I perform the adjust (still don't know how to l link to `target`).... with `bo.maximize(init_points=0, n_iter=5, kappa=5)`

I use the following command to see the type and of `print(type(bo._gp))` and the content I found it here:
> https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html

Naturally I would like to access the methods of this class object but I don't know how.... Focusing on the tutorial demo (first link I quoted). The author used the `mean, sigma = bo._gp.predict(x.reshape(-1,1), return_std=True)` , where `x = np.linspace(-2, 10, 10000)`

I am trying to reproduce this example > https://chaospy.readthedocs.io/en/master/tutorial.html employing GPs....

Looking forward comments and support from the community I salute everyone of you.

Ps.: Sorry for the opened and closed blank issues, my keyboard trolled me...

**Comment by fmfn** [comment]
> Here comes the first TRUE question bo = BayesianOptimization(model,pbounds,verbose=2,random_state=1) How does bo received information to fit to target???

Well, it simply doesn't, you didn't pass `target`, you passed `model`. **At this point** `target` is just another object in your name space that has nothing to do with anything.

This sounds like a GP problem, I don't really see what's the deal with bayesian optimization. The inner GP is not made available via "public" methods or as a `property` precisely because the end user shouldn't really be messing with it directly. In the example notebook the goal was to make a particular kind of visualization, so we look "under the optimizer's hood` to do so.
