### ISSUE TITLE
The order of parameters is not kept

### ISSUE THREAD

**Issue by syrte** [fmfn/BayesianOptimization#214]
I noticed that the order of the target function parameters has been resorted intentionally (introduced in https://github.com/fmfn/BayesianOptimization/pull/121 ). `TargetSpace.__init__` writes
https://github.com/fmfn/BayesianOptimization/blob/600d0c7f7e2a9c30132b5771695084874892ae77/bayes_opt/target_space.py#L44-L50

However, this sometimes gives non-intuitional results. When I use the Gaussian process object `BayesianOptimization._gp`, I found the order of parameters is different from the target function itself in some cases.

I believe this sorting mechanism here was introduced with a good rationale. Nevertheless, considering that dict objects are ordered in Python3 now,  this sorting seems not necessary?

**Comment by syrte** [comment]
What if using 
```python
    self._keys = list(pbounds.keys())
    # Create an array with parameters bounds
    self._bounds = np.array(
        [pbounds[key] for key in self._keys],
        dtype=np.float
    )

```

**Comment by syrte** [comment]
If this change does not affect the rest part of the code and you are happy with it, I'm glad to make a pull request.

**Comment by fmfn** [comment]
Hum, I think the main reason behind it was for consistency and to have things in alphabetical order when needed. I don't feel too strongly about it, but I also wouldn't remove it just for the sake of doing so, remember, not everyone uses python3 (sadly).

If you want to open a PR with this change we can talk further, I just don't like the idea of every time you run the code the parameters are shown in a different order or, even worse, bounds and keys having different orders.

**Comment by bacalfa** [comment]
I just came across this sorting "feature" because it was messing up with the order of the parameters. I was expecting them to follow my defined order, but generated samples follow a sorted order based on the key names. Honestly, I think this sorting shouldn't be done if the sole purpose is to support Python 2, which is deprecated anyway. Anyway, I'll have to enforce the same sorting on my code to avoid problems, which isn't required when using other solvers.
