### ISSUE TITLE
Is there a way to deal with high dimensional data?

### ISSUE THREAD

**Issue by Cinofix** [fmfn/BayesianOptimization#237]
I'd like to optimize a function in a n-dimension space.

**Comment by ben-arnao** [comment]
What is your use case? Vanilla BO doesn't do well with more than 15-20 dimensions.

**Comment by Cinofix** [comment]
I'd like to optimize a vector of n (< 20) coefficients, meaning that the objective function should take in input a vector (not single parameters). 
Moreover, the bounds should be defined for each entry of my vector.

**Comment by ziq-ao** [comment]
I have a similar question. Sometimes I don't (or can't) define an objective function with a specific number of arguments. Take def(x): return np.sum(x) for example, maybe I can define it in a different way like def(x1, x2): return x1+x2. However, if I want to change the dimension of x, I will have to redefine the objective.

Do anyone have any good idea to solve this issue?

**Comment by homeoffice-ys** [comment]
Has anyone found a solution that allows an arbitrary number of input parameters to the objective function?

**Comment by ben-arnao** [comment]
@homeoffice-ys I haven't yet found a good "intelligent" way to do high-dimensional black box optimization. Because of this i created my own solution if you'd like to try it out- https://github.com/ben-arnao/stochasticmutatortuner

My thinking here was to more or less abandon the ideal of building a surrogate model to base your search on. For types of problems like hyperparameter optimization it doesn't seem possible to have a smart search, at least not currently. I've found that most methods that do try to do this, make some pretty big assumptions about the problem and search space that aren't always true.

It probably won't perform quite as well was BO for problems BO is suited for (low dimensions, real-numbers, etc.) but the benefit is that it should be able to handle nested, categorical, and high dimensional parameter space and at least perform better than random search.

**Comment by KhanhThiVo** [comment]
Hi guys,
I was having the same question, as Luis pointed out in #268, we can use a wrapper function that takes **kwargs as parameter. In my case I directly put **kwargs as the input for my black_box_function and create a dict for pbounds according to the number of my dimensions.
Hope this can help those with a similar question.
