### ISSUE TITLE
"ValueError: array must not contain infs or NaNs" happens after self.suggest().

### ISSUE THREAD

**Issue by SunLightFor6** [fmfn/BayesianOptimization#243]
I met an error when executing the code shown in the **Basic tour of the Bayesian Optimization package** part. My code is the same as the demo, except the parameters for maximize() method.
```
def black_box_function(x, y):
    return -x ** 2 - (y - 1) ** 2 + 1

from bayes_opt import BayesianOptimization
pbounds = {'x': (2, 4), 'y': (-3, 3)}

optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds,
    random_state=1,
)

optimizer.maximize(
    init_points=1,
    n_iter=5,
)
print(optimizer.max)
```

As you can see, **I set the parameters as 1 and 5 respectively, and I got the output as well as the error like this:**
```
|   iter    |  target   |     x     |     y     |
-------------------------------------------------
|  1        | -7.135    |  2.834    |  1.322    |
Traceback (most recent call last):
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 169, in maximize
    x_probe = next(self._queue)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 26, in __next__
    raise StopIteration("Queue is empty, no more objects to retrieve.")
StopIteration: Queue is empty, no more objects to retrieve.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmp.py", line 91, in <module>
    n_iter=5,
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 171, in maximize
    x_probe = self.suggest(util)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 124, in suggest
    self._gp.fit(self._space.params, self._space.target)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/sklearn/gaussian_process/_gpr.py", line 234, in fit
    self.kernel_.bounds))]
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/sklearn/gaussian_process/_gpr.py", line 503, in _constrained_optimization
    bounds=bounds)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 600, in minimize
    callback=callback, **options)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 326, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 64, in __call__
    fg = self.fun(x, *args)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/sklearn/gaussian_process/_gpr.py", line 225, in obj_func
    theta, eval_gradient=True, clone_kernel=False)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/sklearn/gaussian_process/_gpr.py", line 476, in log_marginal_likelihood
    alpha = cho_solve((L, True), y_train)  # Line 3
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 196, in cho_solve
    b1 = asarray_chkfinite(b)
  File "/home/ljy/anaconda3/envs/tt/lib/python3.6/site-packages/numpy/lib/function_base.py", line 496, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

It looks something wrong with suggest() fucntion.

And of course, if I set the two hyper-parameters as **2 and 3 respectively,** it works well and does optimize to a good result, the output is like this then.
```
|   iter    |  target   |     x     |     y     |
-------------------------------------------------
|  1        | -7.135    |  2.834    |  1.322    |
|  2        | -7.78     |  2.0      | -1.186    |
|  3        | -7.11     |  2.218    | -0.7867   |
|  4        | -12.4     |  3.66     |  0.9608   |
|  5        | -6.999    |  2.23     | -0.7392   |
=================================================
```
So I'm not sure why I can't set init_points to be smaller, or there are some principles about these two parameters that I haven't understood.

**Comment by ben-arnao** [comment]
I've had this error come up alot. I think it might be easier if we just caught the error and let the user know that all init_points are the same (or nan) so that the problem is a little bit clearer

**Comment by rkern** [comment]
I believe this is due to a change in `scikit-learn` 0.23: https://github.com/scikit-learn/scikit-learn/issues/15612

The `normalize_y=True` option which is used now divides out the standard deviation of the `y` data, not just subtracting the mean. When there is just one data point, this results in a `NaN`.

**Comment by nerai** [comment]
It seems I'm running into the same issue:

```
from bayes_opt import BayesianOptimization, UtilityFunction

def black_box_function(x):
	return x + 5

optimizer = BayesianOptimization(
	f=black_box_function,
	pbounds={'x': (1, 2)},
	verbose=2,
	random_state=1,
)

utility = UtilityFunction(kind="ucb", kappa=2.5, xi=0.0)

for i in range(2):
	print(i)
	next_point = optimizer.suggest(utility)
	print(next_point)
	target = black_box_function(**next_point)
	print(target)
	optimizer.register(params=next_point, target=target)
```

```
0
{'x': 1.4170220047025741}
6.417022004702574
1
array must not contain infs or NaNs
Stack trace:
 >  File "...\module1.py", line 20, in <module>
 >    next_point = optimizer.suggest(utility)
```

I tried to follow the tutorial. I'm not familiar with BO. Is this a problem in the library, or can I fix this myself?

**Comment by rkern** [comment]
As a stopgap, you can downgrade `scikit-learn` to a 0.22.x release.

**Comment by fpnick** [comment]
I think I have a similar, probably related issue with bayesian_optimization==1.2.0 and scikit-learn==0.21.3:

```
File "C:\Users\Fabian.Nick\Documents\01_Projects\**\**\**\bayesopt_gui.py", line 299, in main_sequentiel
    next_point_to_probe = optimizer.suggest(utility)
  File "C:\Users\Fabian.Nick\.conda\envs\Python 3.7 Branko\lib\site-packages\bayes_opt\bayesian_optimization.py", line 128, in suggest
    self._gp.fit(self._space.params, self._space.target)
  File "C:\Users\Fabian.Nick\.conda\envs\Python 3.7 Branko\lib\site-packages\sklearn\gaussian_process\gpr.py", line 185, in fit
    X, y = check_X_y(X, y, multi_output=True, y_numeric=True)
  File "C:\Users\Fabian.Nick\.conda\envs\Python 3.7 Branko\lib\site-packages\sklearn\utils\validation.py", line 719, in check_X_y
    estimator=estimator)
  File "C:\Users\Fabian.Nick\.conda\envs\Python 3.7 Branko\lib\site-packages\sklearn\utils\validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "C:\Users\Fabian.Nick\.conda\envs\Python 3.7 Branko\lib\site-packages\sklearn\utils\validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by dan0nchik** [comment]
Hello! Has the issue been fixed?

**Comment by jakublipinski** [comment]
@dan0nchik see [my comment](https://github.com/fmfn/BayesianOptimization/issues/270#issuecomment-808390661) - maybe it's a reason for your issue too.

**Comment by dan0nchik** [comment]
@jakublipinski Hello! Thanks, but in my case there was another problem. I’m developing a library which used sklearn in 1.0 version, but then I rewrote it without using sklearn, but didn’t see that it was in Bayesian Optimization dependency list 😅

**Comment by samuelstroschein** [comment]
I encountered the same error following the example notebook provided here [https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb). Cell 8 throws the ValueError.

**Comment by vikash0603** [comment]
> I believe this is due to a change in `scikit-learn` 0.23: [scikit-learn/scikit-learn#15612](https://github.com/scikit-learn/scikit-learn/issues/15612)
> 
> The `normalize_y=True` option which is used now divides out the standard deviation of the `y` data, not just subtracting the mean. When there is just one data point, this results in a `NaN`.



> As a stopgap, you can downgrade `scikit-learn` to a 0.22.x release.

I downgraded the scikit-learn to 0.22, still I couldn't solve the issue 

|   iter    |  target   | activa... | batch_... |  epochs   | learni... |  neurons  | optimizer |
-------------------------------------------------------------------------------------------------
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D820C66280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
| 1         | -65.57    | 5.51      | 335.3     | 54.88     | 0.7716    | 36.58     | 1.044     |
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D820F05310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
| 2         | -13.02    | 0.2023    | 536.2     | 39.09     | 0.3443    | 99.16     | 1.664     |
| 3         | -0.2628   | 0.7307    | 735.7     | 69.7      | 0.2815    | 51.96     | 0.8286    |
| 4         | -0.2867   | 1.01      | 723.7     | 59.35     | 0.9437    | 44.38     | 4.815     |
| 5         | -25.86    | 9.0       | 1e+03     | 20.0      | 1.0       | 10.0      | 7.0       |
| 6         | -0.02881  | 9.0       | 651.3     | 100.0     | 0.01      | 100.0     | 7.0       |
| 7         | -37.15    | 9.0       | 736.2     | 20.0      | 1.0       | 100.0     | 7.0       |
| 8         | -34.68    | 1.88      | 723.6     | 55.92     | 0.9136    | 45.54     | 2.813     |
| 9         | nan       | 7.152     | 237.9     | 96.03     | 0.7504    | 47.36     | 5.18      |
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
File ~\AppData\Roaming\Python\Python39\site-packages\bayes_opt\bayesian_optimization.py:306, in BayesianOptimization.maximize(self, init_points, n_iter, acquisition_function, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)
    305 try:
--> 306     x_probe = next(self._queue)
    307 except StopIteration:

File ~\AppData\Roaming\Python\Python39\site-packages\bayes_opt\bayesian_optimization.py:27, in Queue.__next__(self)
     26 if self.empty:
---> 27     raise StopIteration("Queue is empty, no more objects to retrieve.")
     28 obj = self._queue[0]

StopIteration: Queue is empty, no more objects to retrieve.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Input In [17], in <cell line: 2>()
      1 nn_bo = BayesianOptimization(nn_reg_bo, params_nn, random_state=111)
----> 2 nn_bo.maximize(init_points=3, n_iter=10)

File ~\AppData\Roaming\Python\Python39\site-packages\bayes_opt\bayesian_optimization.py:309, in BayesianOptimization.maximize(self, init_points, n_iter, acquisition_function, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)
    307 except StopIteration:
    308     util.update_params()
--> 309     x_probe = self.suggest(util)
    310     iteration += 1
    311 self.probe(x_probe, lazy=False)

File ~\AppData\Roaming\Python\Python39\site-packages\bayes_opt\bayesian_optimization.py:220, in BayesianOptimization.suggest(self, utility_function)
    218 with warnings.catch_warnings():
    219     warnings.simplefilter("ignore")
--> 220     self._gp.fit(self._space.params, self._space.target)
    221     if self.is_constrained:
    222         self.constraint.fit(self._space.params,
    223                             self._space._constraint_values)

File C:\ProgramData\Anaconda3\lib\site-packages\sklearn\gaussian_process\_gpr.py:224, in GaussianProcessRegressor.fit(self, X, y)
    222 else:
    223     dtype, ensure_2d = None, False
--> 224 X, y = self._validate_data(
    225     X,
    226     y,
    227     multi_output=True,
    228     y_numeric=True,
    229     ensure_2d=ensure_2d,
    230     dtype=dtype,
    231 )
    233 # Normalize target value
    234 if self.normalize_y:

File C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:581, in BaseEstimator._validate_data(self, X, y, reset, validate_separately, **check_params)
    579         y = check_array(y, **check_y_params)
    580     else:
--> 581         X, y = check_X_y(X, y, **check_params)
    582     out = X, y
    584 if not no_val_X and check_params.get("ensure_2d", True):

File C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:979, in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
    962     raise ValueError("y cannot be None")
    964 X = check_array(
    965     X,
    966     accept_sparse=accept_sparse,
   (...)
    976     estimator=estimator,
    977 )
--> 979 y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)
    981 check_consistent_length(X, y)
    983 return X, y

File C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:989, in _check_y(y, multi_output, y_numeric)
    987 """Isolated part of check_X_y dedicated to y validation"""
    988 if multi_output:
--> 989     y = check_array(
    990         y, accept_sparse="csr", force_all_finite=True, ensure_2d=False, dtype=None
    991     )
    992 else:
    993     y = column_or_1d(y, warn=True)

File C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:800, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    794         raise ValueError(
    795             "Found array with dim %d. %s expected <= 2."
    796             % (array.ndim, estimator_name)
    797         )
    799     if force_all_finite:
--> 800         _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
    802 if ensure_min_samples > 0:
    803     n_samples = _num_samples(array)

File C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:114, in _assert_all_finite(X, allow_nan, msg_dtype)
    107     if (
    108         allow_nan
    109         and np.isinf(X).any()
    110         or not allow_nan
    111         and not np.isfinite(X).all()
    112     ):
    113         type_err = "infinity" if allow_nan else "NaN, infinity"
--> 114         raise ValueError(
    115             msg_err.format(
    116                 type_err, msg_dtype if msg_dtype is not None else X.dtype
    117             )
    118         )
    119 # for object dtype data, we only check for NaNs (GH-13254)
    120 elif X.dtype == np.dtype("object") and not allow_nan:

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by bwheelz36** [comment]
Hi @vikash0603 

This has not been reported as an issue for quite some time so I am concerned you are still seeing it.
Could I ask you to open a new issue and use the 'bug report' template so we can try to reproduce and fix this?
