### ISSUE TITLE
Ways to skip iteration

### ISSUE THREAD

**Issue by sevagh** [fmfn/BayesianOptimization#289]
Hello - I'd like to sometimes skip an iteration. E.g.:

```
def optimization_fn(arg1, arg2):
    if arg1 == degenerate_condition_1 and arg2 == degenerate_condition 2:
        raise SkipIteration
    return custom_computation(arg1, arg2)
```

I have a case (audio spectrograms) where a specific combination of parameter (minimum, maximum frequency) is unsupported by the length of the input signal. Such conditions are rare.

Is there a way I could somehow insert a custom function that lets me do this?

So, say out of 1,000 iterations, ~30 of them encounter a degenerate condition, I'm ok with a spinlock or a skip iteration. One thing I thought of was to return a large negative value, but I think that would affect the state of the underlying Bayesian optimization, which I don't want to do.

**Comment by sevagh** [comment]
I think the constraints is what I'm looking for - https://github.com/fmfn/BayesianOptimization/issues/284

**Comment by sevagh** [comment]
Another person suggesting a large negative penalty: https://github.com/fmfn/BayesianOptimization/issues/266

**Comment by bwheelz36** [comment]
Hey sevagh, the way I do this is indeed just by returning a constant number where such conditions occur. I would suggest not making it too large with respect to the rest of the objective function values, because that seems to throw off the fitting of the Gaussian process. Just make it large enough to clearly indicate it's a bad solution (e.g. if you hope to find an OF of 100, -100 should be fine)
From what I understand, [from reading through these forums](https://github.com/fmfn/BayesianOptimization/pull/95), the constraints feature isn't entirely implemented/ supported yet.

**Comment by sevagh** [comment]
I will try returning -80 (the worst legitimate score of my OF) instead of `float('-inf')` and see how that goes.
