### ISSUE TITLE
How to evaluate specific point?

### ISSUE THREAD

**Issue by NCLHILL** [fmfn/BayesianOptimization#295]
When the Bayesian model is trained. How can get the evaluation values of some special points?

**Comment by bwheelz36** [comment]
assuming that your instance of BayesianOptimization is called optimizer, and has been appropriately set up and trained:

```python
next_point_to_probe = optimizer.suggest(utility)
mean, std = optimizer._gp.predict(NextPointValues.reshape(1, -1), return_std=True)
```

I've used the next_point_to_probe variable because it will return values in the right order, shape etc. But if you want to probe some different point to replace the values with your own.
You can also test a series of points, by passing array. Just experiment to get the dimensions right. 

If that answers your question can you close the issue?
