### ISSUE TITLE
constrained bayesian optimization

### ISSUE THREAD

**Issue by merdan-9** [fmfn/BayesianOptimization#304]
Hi,
 
Is it possible to model constrained via Gaussian process? (especially implicit constrained, like max tracking error, which is not the constrained of the parameter) Then output the best parameter based on cost and constraint?

Thanks, and have a nice day!

**Comment by bwheelz36** [comment]
Do you mean that parameters should be able to be constrained as e.g. a function of other parameters?

if so, then this has been discussed at length if you search through the issues. It is not possible in the current version, although there are pull requests on here, which if you could implement yourself if you really want to.... 
https://github.com/fmfn/BayesianOptimization/pull/95
But if you read through the link above, the lead dev on this repository has some concerns about this approach.

Otherwise, the current way you can handle this is by penalizing such cases in the objective function,  see #289
