### ISSUE TITLE
How to code bounds with multiple range?

### ISSUE THREAD

**Issue by pianistprogrammer** [fmfn/BayesianOptimization#357]
Is it possible to have the pbounds take values from a certain multiple?
For example if `x': (12,20)` with the multiples of 2, so that the x will have values such as 12, 14 16, 18, 20 and not take the odd numbers.
just like in python range(12,20,2)

**Comment by till-m** [comment]
Hi @pianistprogrammer,

I would decompose these particular constraints into two parts. I assume you're familiar with restricting the optimization to integer parameters, otherwise see [here](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb). There are more sophisticated solutions that may have better convergence, see #191 but that is probably overkill for your problem.
Next, to assure that the solutions are divisible by a certain number you can use surrogate functions. Assume you're trying to optimize a function like this

```python
def func_with_discrete_even_params(x, y, d):
    # Simulate necessity of having d being discrete and even.
    assert type(d) == int
    assert d % 2 == 0
    
    return ((x + y + d) // (1 + d)) / (1 + (x + y) ** 2)
```

you can use a surrogate function;

```python


def function_to_be_optimized(x, y, w):
    d = 2 * int(w)
    return func_with_discrete_params(x, y, d)
```

and adjust the bounds accordingly:

```python
optimizer = BayesianOptimization(
    f=function_to_be_optimized,
    pbounds={'x': (-10, 10), 'y': (-10, 10), 'w': (6, 10)}, # w in [6, 10] => d in {12, 14, ..., 20]
    verbose=2,
    random_state=1,
)
```

Let me know if this helps.

**Comment by pianistprogrammer** [comment]
![Screenshot 2022-09-27 at 21 25 33](https://user-images.githubusercontent.com/26509372/192617618-07786832-fac0-434b-b627-5a5357009fc3.png)
Thank for helping out, I had the same idea too after checking the discrete parameters in the advanced notebook examples. However, I noticed that the values of w still has odd numbers like 11, 7 , 9 in a bound of (2, 20) as you can see from the screenshot I pasted here, how do I deal with this. I thought I should only get even numbers in the result

**Comment by bwheelz36** [comment]
Hey @pianistprogrammer (that's a cool username btw!)

`w` will still take odd integer values, however `d` can only be even since `d=2*w`. Essentially you are re-parameterizing your problem. So in this case `d` would be the variable you actually care about, even though `w` is what you allow the optimizer to vary.

**Comment by pianistprogrammer** [comment]
@bwheelz36 lol. Thanks for the explanation. Maybe my challenge now is how to read the final result. For this example, if x = 10, y = 3 and w = 11 are the values for the optimal solution of 0.005733, how do I factor in d ? , cause i could also write 
` w = 2 * int(w)` instead of d and the result would be the same

**Comment by bwheelz36** [comment]
d = 2 * int(w)
if w = 11
d = 22

**Comment by pianistprogrammer** [comment]
Thank you, I tried a small example here and saw that the result of the function - the target - also changes because of the multiplication by 2. Now I perfectly understand what is going on. Thanks once again
