### ISSUE TITLE
Can't reproduce the results in the example

### ISSUE THREAD

**Issue by ytang322** [fmfn/BayesianOptimization#359]
Hi,
I am getting different results than those in the example. I downloaded the whole package and didn't change anything. For the basic-tour, I am getting following results in [5]:

![p1](https://user-images.githubusercontent.com/43100454/194707253-6852b250-b606-4de0-83e4-d0b6c9b4be2a.JPG)
But the results in the example is:
![p3](https://user-images.githubusercontent.com/43100454/194735878-14cb7b9e-26dc-4c1d-a1a8-bfe23db922d0.JPG)

For visualization file, I am also getting different results. There is a warning when I run visualization:
![p2](https://user-images.githubusercontent.com/43100454/194707233-daadb351-eb73-4cb0-819d-386ba25a8886.JPG)
The results are consistent on both my computers. 
I am really confused why the codes have different results on my computers. 
Thank you!

**Comment by bwheelz36** [comment]
Hi

- regarding different results: the results in the example were generated three years ago, using a different version of the code and different supporting libraries, so I am not surprised that they don't match with what is currently produced. This isn't a concern - these first guesses are essentially random anyway.
- Regarding the warning in the visualization example: I can't reproduce what you are seeing, but I also wouldn't worry about it. This warning is simply saying that the best length scale found is close to the lower bounds. You can change these if you want to by setting a [custom kernel](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.Matern.html) like this:
```python
from sklearn.gaussian_process.kernels import Matern
kernel = Matern(length_scale=1.0, length_scale_bounds=(1e-05, 100000.0), nu=1.5)
optimizer.set_gp_params(kernel=kernel)
```
- but in this case I wouldn't bothe. You only entered one iteration so whatever length scales it found are probably rubbish anyway, because it is trying to fit a model based on almost no data. So I wouldn't worry about this warning.
- As a general comment, it is much easier to help if you post code as [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) instead of pictures. For example, my attempt to reproduce the warning you see above:

```python


from bayes_opt import BayesianOptimization
from bayes_opt import UtilityFunction
import numpy as np

import matplotlib.pyplot as plt
from matplotlib import gridspec

def target(x):
    return np.exp(-(x - 2)**2) + np.exp(-(x - 6)**2/10) + 1/ (x**2 + 1)

optimizer = BayesianOptimization(target, {'x': (-2, 10)}, random_state=27)
optimizer.maximize(init_points=0, n_iter=1, kappa=5)
```

**Comment by ytang322** [comment]
Thanks a lot!
