### ISSUE TITLE
init_points when using the Suggest-Evaluate-Register Paradigm & more

### ISSUE THREAD

**Issue by xshang93** [fmfn/BayesianOptimization#380]
Hi, thanks for this great piece of software. I have been playing with it for some time and would like to get some experts' opinion on some of the issues I'm facing now.
- Is there a way to let the optimiser explore more initial points in the Suggest-Evaluate-Register Paradigm? 
- If there is an 'invalidate' point during the optimisation iterations, what is the best way to 'skip' that invalid point? So far I'm using a try/except structure to throw a constant value as the output of my blackbox function, and then tell the optimiser to only register a point when the output is not that constant value. Is this the right way to do it?
- Is there a 'maximum' number of input parameters BO can handle? I read somewhere that it shouldn't exceed 20 but not sure how reliable this is.
- Lastly a general question about BO. Do the input parameters of BO need to be a 'direct' observation of the blackbox function? For example, if I have n points (x_1 to x_n) and the output is simply y = sum(x_1 to x_n). Instead of using x_1 to x_n as inputs, I create a new variable 'idx', and each 'idx' corresponds to a unique set of numbers x_1 to x_n. You can think of idx as a random seed that we use to generate n numbers in Python. Will this be a valid optimisation problem that BO can solve? My intuition tells me yes since BO sees the random number generation as part of the blackbox function, but I wanted to get some other opinions.

Thanks!
Xiao

**Comment by till-m** [comment]
Hi Xiao,

You're asking a number of interesting questions here, and the answers might not be super straightforward. I hope I can give you some pointers though:

1) The `init_points` are simply sampled using `optimizer._space.random_sample()` so you can just call that function to get a random point to sample and do that as often as you want.

2) It would be helpful to know what you're trying to do here, i.e. why you want to invalidate some points. The approach you're describing probably works, but might not be ideal.

3) I assume that by "number of input parameters" you're referring to the dimension, in that case the reason for BO being bad for high dimension is that you require a large number of samples due to the curse of dimensionality. However, both the sampling from a computationally expensive target function, as well as some linear algebra routines that are perfomed internally for the GP regression scale poorly. In that sense, BO might start to perform poorly, i.e. take a lot of samples and, as a result, a lot of (computing) time to find maxima, but it will not suddenly stop working. Statements like the one you read are helpful as heuristic guideline, but you can (and should!) experiment and see whether BO is a feasible choice for your optimization problem.

4) BO uses GP regression to approximate a function from samples. For this purpose, kernels are employed which are essentially a distance metric, i.e. points that are close according to the kernel are assumed to be somewhat similar. For your example, which to my understanding essentially corresponds to approximating a hashmap, this will not work since your random seeds are disconnected from any actual function values.

Hope this helps.

**Comment by xshang93** [comment]
Thank you very much for the reply. Some further comments/questions from me:
> 
> 2. It would be helpful to know what you're trying to do here, i.e. why you want to invalidate some points. The approach you're describing probably works, but might not be ideal.

It's hard to describe in detail what I'm doing, but essentially within the blackbox function I'm first generating a geometry, which will then be evaluated to get a numerical output. Some of the geometries are just not feasible, which are the ones I wanted to skip.

> 4. BO uses GP regression to approximate a function from samples. For this purpose, kernels are employed which are essentially a distance metric, i.e. points that are close according to the kernel are assumed to be somewhat similar. For your example, which to my understanding essentially corresponds to approximating a hashmap, this will not work since your random seeds are disconnected from any actual function values.
> 

For this, my thoughts are: in a computer the random numbers are not real 'random' numbers and they are generated following some math function. This function (let's call it rand_gen) takes a random seed as input and n numbers as output. This way, the random seeds are directly connected to the output of rand_gen, which will then connect to the rest of the blackbox function I'm optimising. Am I missing something here? One weird thing is that, when I ran BO this way, it actually works and would converge to the maximum value in my dataset (As shown in the image below).

Thanks!
![Target vs optimization iteration20221115_50ms_1ori_25grains_alpha_1e-1_cust_func_100iter_ori_ratiorange](https://user-images.githubusercontent.com/86078353/202928484-61fc4c49-16a8-48e7-92a0-cb3019c720c4.png)

**Comment by till-m** [comment]
Hi Xiao,

> 2.

You can skip registering these points, but if valid geometries form regions it might be the case that the optimizer gets stuck in a region and keeps suggesting points there, essentially halting your optimization. If that is the case, it might be better to register a low value for the corresponding point to make sampling that region less attractive.

> 4.

Ultimately, by choosing the kernel to use for BO one is making the assumption that the function one is modelling is part of a family of functions that are generated by GP regression with a specfic kernel. I would encourage you to scroll through [this document](https://scikit-learn.org/stable/modules/gaussian_process.html#radial-basis-function-rbf-kernel) to see how a specific kernel choice is associated with a specific family of functions. The default for this package is the Matérn Kernel, which produces very flexible continuous, but not necessarily smooth, functions.

Presumably the hashmap you are approximating is not continuous, as such I would expect a poor performance of BO. As for why your results look like this, it might be hard to say in vacuum and without the code that produces them. However, I would expect sequentially sampling random points to produce equal results (and having less computational overhead), since your function has no discernible structure for _any_ learner to exploit.

**Comment by xshang93** [comment]
I think I'm slowing gaining a clearer image of what's going on.
> 
> Ultimately, by choosing the kernel to use for BO one is making the assumption that the function one is modelling is part of a family of functions that are generated by GP regression with a specfic kernel. I would encourage you to scroll through [this document](https://scikit-learn.org/stable/modules/gaussian_process.html#radial-basis-function-rbf-kernel) to see how a specific kernel choice is associated with a specific family of functions. The default for this package is the Matérn Kernel, which produces very flexible continuous, but not necessarily smooth, functions.
> 

I guess I don't have a clear idea on what my blackbox function is like. Is it beneficial to play with different kernels? Or even some manipulation cross different kernels? But I feel the first thing for me to do is to judge if BO is the right method for my problem.

> Presumably the hashmap you are approximating is not continuous, as such I would expect a poor performance of BO. As for why your results look like this, it might be hard to say in vacuum and without the code that produces them. However, I would expect sequentially sampling random points to produce equal results (and having less computational overhead), since your function has no discernible structure for _any_ learner to exploit.

I think you are right on this. Does this mean my problem is not suitable for BO to solve? If so, is there any other optimization method that you would suggest? I understand it's very hard for you to say anything without a context - would you mind sharing with me an email so I can send in some details on what I'm working on? Of course please feel free to say no

Thanks,
Xiao

**Comment by till-m** [comment]
Hi Xiao,

honestly, if I understand your problem correctly there should be no structure an optimizer can exploit and you're stuck with brute forcing the problem (unless you have a quantum computer, then you might employ Grover's algorithm/Grover adaptive search ;)).

I will post my email in another reply and we can discuss privately.

**Comment by till-m** [comment]
You can reach me at till /dot/ muser /at/ sdsc /dot/ ethz /dot/ ch :)

**Comment by bwheelz36** [comment]
> " Does this mean my problem is not suitable for BO to solve? If so, is there any other optimization method that you would suggest?"

Just to add my two cents (I do not want to imply I am an expert here but this is my understanding)

In general, for 'black box' objectives, there are probably two 'best in class' approaches.
One is Bayesian Optimization, and the other is genetic optimization.
If your objective function is expensive to evaluate, then Bayesian is probably the best choice. If it is cheap, a genetic approach may be superior. 

Fundamentally, these algorithms to assume that over some scale, the objective function is continuous. In other words, both of them assume that it is possible to make a reasonable prediction of the performance an unseen solution, based on other solutions that are close by in the objective space. What is mean by 'small' depends on the objective function, and in Bayesian Optimization is governed by the length scales.
If this is really not the case, then like @till-m  says, basically no algorithm will work. However, I suspect you will find that at least over some small length scale, clustered solutions are correlated. 
If your objective is quite complicated, it can absolutely be worth playing around with the kernel in the gaussian process. A good test is to compare the predictions it makes to the actual measured data. You can see an example of this in #287.

**Comment by till-m** [comment]
> close by in the objective space

I think another key thing here is that it is up to you to define what this means, in the BO case by adjusting the kernel (especially the length scale + the distance functions of Matérn and RBF) and in the genetic algorithm e.g. the genetic representation and crossover strategy.

**Comment by xshang93** [comment]
>> A good test is to compare the predictions it makes to the actual measured data. You can see an example of this in #287.

Hey, thanks a lot for the comments. I was reading through #287 and the graphs you have there, and I just wanted to confirm if the x axis of your graphs are iteration number or the actual input x?

**Comment by bwheelz36** [comment]
x axis is iteration - in those plots there were around 8 parameters being tuned.
Have a read through [this](https://stats.stackexchange.com/questions/445484/does-length-scale-of-the-kernel-in-gaussian-process-directly-relates-to-correlat) for a discussion on length scales. 

The length scales actually get tuned behind the scenes, so while a good starting guess helps, in many situations it doesn't need to be **that** good. I would suggest using #287 as an example, and see how you go. 
If I understood your plot above - is the optimization already working? The other aspect of all this is 'if it's working don't worry about it' :-P

**Comment by xshang93** [comment]
> x axis is iteration - in those plots there were around 8 parameters being tuned. Have a read through [this](https://stats.stackexchange.com/questions/445484/does-length-scale-of-the-kernel-in-gaussian-process-directly-relates-to-correlat) for a discussion on length scales.
> 

Sorry I guess I didn't completely understand your plots then - how did you get the output of the GPR?

> The length scales actually get tuned behind the scenes, so while a good starting guess helps, in many situations it doesn't need to be **that** good. I would suggest using #287 as an example, and see how you go. If I understood your plot above - is the optimization already working? The other aspect of all this is 'if it's working don't worry about it' :-P

lol I wish it was working but I couldn't seem to justify it. The process involved some random seeds generation that I couldn't easily trust. I'm currently setting a 10% lengthscale as you suggested in #287 and I hope it could work

**Comment by bwheelz36** [comment]
> " how did you get the output of the GPR?"

good point, this isn't really properly documented.
You can use `optimizer._gp.predict()` method.
see #295 for an example

**Comment by xshang93** [comment]
> > " how did you get the output of the GPR?"
> 
> good point, this isn't really properly documented. You can use `optimizer._gp.predict()` method. see #295 for an example

Got it. One thing I noticed from your plots in #287 though, it seems like GPR is producing a good fit from iteration 0. Is this an expected behaviour? Intuitively I would expect it to do badly at the beginning but improve overtime

**Comment by bwheelz36** [comment]
I can't completely remember anymore, but looking at that graph, I'm pretty sure I was testing **retrospective** fit - so the ability of the gp to predict points it has already seen. 
This is obviously something that **should** happen, but it's a good starting point to make sure you have some decent kernel settings.

**Comment by xshang93** [comment]
> I can't completely remember anymore, but looking at that graph, I'm pretty sure I was testing **retrospective** fit - so the ability of the gp to predict points it has already seen. This is obviously something that **should** happen, but it's a good starting point to make sure you have some decent kernel settings.

Sorry I guess I'm taking the topic away but, I'm not sure if I understand what a retrospective fit is. It sounds interesting but I can't seem to find much about it googling. Could you explain a bit more?

By the way, after adjusting the length scale it seems to perform better, but I'm still not sure if it's working as the results still fluctuates quite a lot. Below on top is 10% length scale, bottom is default length scale.
![Target vs optimization iteration20221128_lengthscale_aplha_ratio_ori0_10_100iter](https://user-images.githubusercontent.com/86078353/204654918-388c4d1f-9751-45b9-83df-327ca68ad826.png)

![Target vs optimization iteration20221119_new_code_alphaRatio_ori0_200iter](https://user-images.githubusercontent.com/86078353/204654957-45237be0-a183-4d7c-99ad-0271bf72a23b.png)

**Comment by bwheelz36** [comment]
OK, by retrospective fit, I mean I have assessed the value of the objective function at some points, registered that point, then updated the gaussian process model. Therefore when I ask for a prediction at that point, it **should** be accurate since we are only asking it to predict something it's already seen. If it's not, then the model has no hope of predicting points it **hasn't** seen, which should be the next test...

[This is my code](https://github.com/ACRF-Image-X-Institute/TopasOpt/blob/master/TopasOpt/Optimisers.py#L985) which uses this package. At each iteration, I:
- get a point to probe
- get the gp prediction
- explicitly asess the point to prove
- log both the prediction and the true value
- You can then compare the predictions versus iteration number; you should see that they are getting better if the code is working
