### ISSUE TITLE
Exception: Bad point. Try increasing theta0.

### ISSUE THREAD

**Issue by jmhessel** [fmfn/BayesianOptimization#4]
I'm not really sure where this error results from -- I am not so familiar with the GP backend from sklearn.

Here's the stack trace. It happens at iteration number 86, but it's inconsistent.

Traceback (most recent call last):
...
    bo.maximize(init_points = 15, n_iter=100)
  File "build/bdist.linux-x86_64/egg/bayes_opt/bayesian_optimization.py", line 314, in maximize
  File "/share/apps/python-2.7.9/lib/python2.7/site-packages/sklearn/gaussian_process/gaussian_process.py", line 352, in fit
    raise Exception("Bad point. Try increasing theta0.")
Exception: Bad point. Try increasing theta0.

**Comment by jmhessel** [comment]
My function I'm trying to optimize looks like this
```
def crossValScore(c):
        scores = []
        for trainI, testI in StratifiedShuffleSplit(y, 10, test_size=.1,):
            lr = LR(C=c)
            Xtr = X[trainI,:]
            ytr = y[trainI]

            Xts = X[testI,:]
            yts = y[testI]

            lr.fit(Xtr, ytr)
            scores.append(f1_score(yts, lr.predict(Xts)))
        scores = np.array(scores)
        return np.mean(scores)
```

my call looks like 
```
 bo = BayesianOptimization(crossValScore, {'c':(.00001, 100000)})
    bo.maximize(init_points = 15, n_iter=100)
```

**Comment by fmfn** [comment]
This is sklearn's GP object complaining. I believe that due to the vastly different scales between lower and upper bounds it makes it a bit harder on the GP.

You can follow their instruction and increase theta0, or increasing the nugget can help sometimes as well. To so you may simply pass these as parameters to `maximize`, which will redirect them to the GP object.

The default value for theta0 is: `theta0=numpy.random.uniform(0.001, 0.05, n_params)`

Alternatively you can either narrow down the search space, or log-transform it, something along the lines of:

    def crossValScore(log_c):
        c = exp(log_c)
        ...

and adjust the bounds accordingly.

**Comment by jmhessel** [comment]
I log-transformed it and am not getting the error -- thanks!
