### ISSUE TITLE
Allow Prior Guesses for Parameters?

### ISSUE THREAD

**Issue by adamwlev** [fmfn/BayesianOptimization#42]
Hey there, thank you so much for this project, I use it all the time and really get a lot out of it. I have a question/idea for a possible enhancement. Would it be difficult to allow a user a guess (and maybe some certainty level) of the optimal value of each parameter in addition to specifying the region to search over? Do you think this would be keeping with the idea behind the project? For me, I often feel that I have a strong sense of where the right parameters are but want to allow for a decent sized range in case I am wrong.

**Comment by fmfn** [comment]
That is an interesting question.

There is a "hack" in place that does something along these lines, the `explore` method. You can pass combinations of parameters you want the optimizer to probe, and it will do so when initializing.

    bo.explore({'x': [-1, 3], 'y': [-2, 2]})

will add the points (-1, -2) and (3, 2), to the list of initialization points (together with some other points drawn at random. Obviously this is not a formal approach to your question, and has limited scope, but in case you didn't know about it, might be of help.

But yes, I would love a feature where the user could pass arbitrary parameter subspaces as having a strong "gut feeling" prior, and let the model handle it. I believe a carefully constructed kernel could encode this information (since it dictates the general type of function the GP can model), however actually translating it to an user friendly UI might be hard.

I'll see if I can play around with it a bit.

**Comment by adamwlev** [comment]
Thank you sir, I think the explore feature is great and had not been leveraging it fully. Appreciate the response. I don't really consider prior guessing to be all that important of a feature now, so please feel free to close this issue..
