### ISSUE TITLE
issues with tensroflow models

### ISSUE THREAD

**Issue by wen036** [fmfn/BayesianOptimization#48]
Hello, I tried to use this package with tensorflow. I defined a function, wrapping all tensorflow related code there, then use BayesianOptimization to optimize learning_rate, batch_size, etc. However, after 4-7 iterations, it gave a "dead kernel" error and stopped running. Please let me know if you have any insights. 
Thanks,
Xuejin

**Comment by jvmancuso** [comment]
I'm assuming you're using Jupyter notebooks from the "dead kernel" speak.  

A Jupyter kernel often dies from resource limitations (e.g. when your program is requesting more memory than has been allocated to the kernel).  Since you're trying to tune batch size with a hyperparameter search, it's highly likely that you're searching values of batch size that require more memory than you've got available.  This is mentioned about Tensorflow specifically [here](http://stackoverflow.com/questions/41386795/tensorflow-saver-kernel-appears-to-have-died).  I would recommend tuning batch size by hand before using Bayesian optimization.  Common choices for batch size are 32, 64, 128.  It mostly depends on how much data you have and your memory resources, but many people go with defaults of 32 or 64.  

Closing this issue since it has nothing to do with this package specifically.
