### ISSUE TITLE
Pass in an objective function

### ISSUE THREAD

**Issue by jonhilgart22** [fmfn/BayesianOptimization#55]
Hi there,

I'm trying to maximize negative mean squared error, but I keep running into this bug. 

`TypeError: hyp_choice_sklearn() got an unexpected keyword argument x`

Here is my code.

```
def hyp_choice_sklearn(hyperparameter_value,hyperparameter_value_two, y_tra = y_train,
 X_tra = X_train, X_tes = X_test, y_tes = y_test):
    nmse = - mean_squared_error(y_tes,
                                GradientBoostingRegressor(n_estimators=hyperparameter_value,
                                max_depth =hyperparameter_value_two).fit(X_tra.as_matrix()
                                ,y_tra.as_matrix()).predict( X_tes.as_matrix()))
    return nmse




bayes_opt_hyp = BayesianOptimization(hyp_choice_sklearn,
                          {'x': (1, 700),'y':(1,50) }) # the bounds to explore
bayes_opt_hyp .explore({'x': np.linspace(1,700,140),'y':np.linspace(1,50,140) }) # the points to explore, need the same size
bayes_opt_hyp.maximize(init_points=1, n_iter=10, acq='ei') # ten steps
```

Any idea what I'm doing wrong?

Also, unrelated but it would be nice to be able to search over different sized domains for each parameter. 

Cheers!

**Comment by fmfn** [comment]
Neither `x` or `y` are parameters of `hyp_choice_sklearn`, and yet you're telling the optimization that `x` and `y` should be optimized.

Either change your function definition to `hyp_choice_sklearn(x, y, ...)` and make the corresponding changes to the body of the function, or change the declaration of `bayes_opt_hyp` to optimize for the correctly named parameters: `{'hyperparameter_value': (1, 700), 'hyperparameter_value_two':(1, 50)}`

I'm not sure I understood your request, can you expand on it a bit?

**Comment by jonhilgart22** [comment]
I didn't realize I needed the name the arguments the same as what I was passing to the optimization package. Thanks!

For different sized domains, it would be nice to be able to search over the following for gadient boosting.

```bayes_opt_hyp .explore({'hyperparameter_value': range(1,700),'hyperparameter_value_two':range(1,50)})```

But this throws the error, ```ValueError: The same number of initialization points must be entered for every parameter.```

**Comment by fmfn** [comment]
I see. The problem here is that explore takes a set of parameters points, and evaluates the function at that point. To do what you are trying you should mesh the two ranges first, generating all the possible pair of parameters combinations.

Say you want to explore `x E (1, 2, 3)`, and `y E (4, 5)`, you would need to create all pairs:
`[1, 4], [1, 5], [2, 4], [2, 5], [3, 4], [3, 5]`, and pass each as a parameter combination.

However notice that the number of points generated is exponential in the number of features you have - you're running a grid search, and that's precisely the problem Bayesian Optimization is trying to solve. So I urge you to not do that and, instead, increase the number of initialization points of the `maximize` method.
