### ISSUE TITLE
Low variances in plots 

### ISSUE THREAD

**Issue by DanielFNG** [fmfn/BayesianOptimization#59]
I'm trying to use this package for conducting an experiment with a design variable, and altering this variable to test performance. I don't know my objective function but I can sample from it. Values are in the range [200, 600]. 

When I try to plot the diagrams from the visualisation notebook, the mean looks alright but the variances are tiny, resulting in extremely tight 95% confidence intervals. I'm using the same functions (posterior, plot_gp) given in the visualisation notebook. All the examples I could find seem to have outputs within [-2,2]. 

Am I missing some sort of scaling step? Is this something that I'll have to change the default kernel, for? I notice that the default is a Matern kernel, but can't see an obvious way to access/change the length scale parameter, if this is even what's required. 

Any help would be much appreciated. Cheers!

**Comment by fmfn** [comment]
No values are scaled behind the scenes, so that could be a reason. Changing the kernel could help, if you know (or suspect) of any behaviour pattern of your target function, adding it to the kernel is often a good idea (if your function is nice and smooth, RBF kernel might be the right choice, for example).

Ultimately it seems this is related to the Gaussian Process step, and not the optimization part of the problem. Fitting GPs can often be really challenging, so I suggest you take a closer look at all the knobs you have control over and give them a try: [GP](http://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html).

Keyword arguments are passed to the underlying GP object, so you can simply do something like:

    gp_params = {'kernel': None, 'alpha': 1e-5}
    bo.maximize(n_iter=5, **gp_params)

And try out other configurations.
