### ISSUE TITLE
Feature selection using BayesianOptimization

### ISSUE THREAD

**Issue by eranop** [fmfn/BayesianOptimization#72]
Is there a way to enter all the combinations of your features as a "Hyper Parameter" so that the optimization will try to maximize the features selected as well as the hyper parameters selected?

**Comment by fmfn** [comment]
You can do whatever you want inside your target function. So as long as you can parametrize you feature combination you can (try to) optimize it. Now, whether or not you are going to be successful is another story.

One way you could do it is to add parameters such as `include_feature_i` to the target function, and inside it perform the appropriate data preprocessing steps to include or not each feature based on their parameter.

I'm not sure if this is going to work well, though, since this method may not be well suited for it. If you parametrize the feature selection space you likely end-up with a highly discontinuous target function in that subspace.

**Comment by eranop** [comment]
I see... 
I can also run comb(1:n_features) iterations (of BO) and for each combination, BO will optimize the hyper parameters and restore the best result. the maximum result out of this will be the best features and the best hyper parameters.
If BO converges after few iterations this solution is computable for few features.
