### ISSUE TITLE
Integrating a MLP with BO

### ISSUE THREAD

**Issue by spadavec** [fmfn/BayesianOptimization#86]
Forgive my ignorance (as I am relatively new to this) but I would like to be able to use this codebase to efficient search 'chemical' space (searching vector space learned via an autoencoder), with a target function that is a multi-layer perceptron that returns estimates of a molecular property (built on a different sequential model) that I want to minimize. In this case, then, I have a few questions: 

1) Wouldn't it be best to supply an `init_points` equal to the number of training data points that I used to train my other MLP, instead of the traditional 2 or 3? 

2) in the example code: 
```python
 bo.maximize(init_points=2, n_iter=0, acq='ucb', kappa=5)
```
Does the `bo.maximize` refer to the maximizing of the expected y-value of your target function, or does it maximize whatever your acquisition function? In my case, I'd like to minimize the output of the target function.

**Comment by fmfn** [comment]
1. The `init_points` method has no connection to the training of your MLP, in fact it doesn't even know (or cares) that the function you're optimizing involves the training of another algorithm. The only reason for it to exist is to prime the Gaussian Process that effectively dictates the parameter search. So much so that one could argue that the only sensible choice for init points is 1.

2. `maximize` will attempt to find the parameter combination that maximizes the output of your function, whatever that is. While it is true that we look to maximums of the acquisition function in the process, this is only a proxy optimization to aid with the parameter search.

I hope that helps and sorry for the delay.
